/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-07-02 06:46:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.auth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!-- saved from url=(0041)http://storage.thucloud.com:7088/register -->\n");
      out.write("<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write(" <meta charset=\"utf-8\">\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write(" <meta name=\"description\" content=\"LC云盘\">\n");
      out.write(" <meta name=\"author\" content=\"xiaohe\">\n");
      out.write("<title>LC云盘</title>\n");
      out.write("<link rel=\"shortcut icon\" href=\"https://www.fangcloud.com/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("<link href=\"../Resources/file/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"../Resources/file/style.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"../Resources/file/sticky-footer-navbar.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"../Resources/file/register.css\" rel=\"stylesheet\">\n");
      out.write(" </head>\n");
      out.write(" <body>\n");
      out.write("<div id=\"wrap\">\n");
      out.write("  <!-- Fixed navbar -->\n");
      out.write("  <div class=\"navbar navbar-fixed-top\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"navbar-header\">\n");
      out.write("        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("        </button>\n");
      out.write("            <a id=\"logo_48_196\" href=\"..\" title=\"Lc云盘\"><img src=\"../Resources/images/lc_meitu_1.png\"/></a>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"collapse navbar-collapse\">\n");
      out.write("        <ul class=\"nav navbar-nav \">\n");
      out.write("        </ul>\n");
      out.write("      </div><!--/.nav-collapse -->\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("      <!-- Begin page content -->\n");
      out.write("<div class=\"container\">\n");
      out.write("  \n");
      out.write(" <form action=\"../register\" method=\"POST\"  class=\"form-horizontal form-register\" role=\"form\">\n");
      out.write("      <div class=\"form-group\">  \n");
      out.write("        <!--[if lte IE 9]> <label>邮箱</label><![endif]-->    \n");
      out.write("        <input class=\"form-control\" type=\"text\" name=\"email\" value=\"\" id=\"email\" placeholder=\"邮箱\" required=\"\">\n");
      out.write("    \n");
      out.write("        <span class=\"help-block\" id=\"email_error\"></span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">    \n");
      out.write("        <!--[if lte IE 9]> <label>昵称</label><![endif]-->    \n");
      out.write("         <input class=\"form-control\" type=\"text\" name=\"nickname\" id=\"nickname\" value=\"\" placeholder=\"昵称\" required=\"\">\n");
      out.write("    \n");
      out.write("         <span class=\"help-block\" id=\"nickname_error\"></span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <!--[if lte IE 9]> <label>密码</label><![endif]-->    \n");
      out.write("        <input class=\"form-control\" type=\"password\" name=\"password\" id=\"password\" value=\"\" placeholder=\"密码\" required=\"\">\n");
      out.write("        <span class=\"help-block\" id=\"password_error\"></span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <!--[if lte IE 9]> <label>确认密码</label><![endif]-->    \n");
      out.write("        <input class=\"form-control\" type=\"password\" name=\"password_confirm\" value=\"\" id=\"password_confirm\" placeholder=\"确认密码\" required=\"\">\n");
      out.write("        <span class=\"help-block\" id=\"confirm_error\"></span>\n");
      out.write("        <span class=\"help-block\" id=\"password_confirm_error\"></span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        <input type=\"submit\" value=\"注册\" class=\"btn btn-primary btn-block\" id=\"is_disable\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("        已经有账号？点击<a href=\"http://localhost:8080/cloud_disk\">登录</a>\n");
      out.write("    </div>\n");
      out.write(" \n");
      out.write("  </form>\n");
      out.write("  \n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div id=\"footer\">\n");
      out.write("\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <p class=\"text-muted credit text-center\">软件工程 LC云盘oss开发小组 copyright ©2016<br>\n");
      out.write("    <a href=\"..\">联系我们</a>‎‎‎\n");
      out.write("        <!--\n");
      out.write("    <script type=\"text/javascript\">var cnzz_protocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");document.write(unescape(\"%3Cspan id='cnzz_stat_icon_1000075329'%3E%3C/span%3E%3Cscript src='\" + cnzz_protocol + \"s22.cnzz.com/z_stat.php%3Fid%3D1000075329%26show%3Dpic' type='text/javascript'%3E%3C/script%3E\"));</script>\n");
      out.write("    -->\n");
      out.write("    </p>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap core JavaScript\n");
      out.write("    ================================================== -->\n");
      out.write("   <!-- <script src=\"/static/js/jquery.js\"></script>\n");
      out.write("    <script src=\"/static/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("-->\n");
      out.write("    <script src=\"../Resources/file/jquery.js\"></script>\n");
      out.write("    <script src=\"../Resources/file/bootstrap.min.js\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("       //console.log(\"ok\");\n");
      out.write("  var ele = { //存放各个input字段obj\n");
      out.write("    email: document.getElementById(\"email\"),\n");
      out.write("    nickname: document.getElementById(\"nickname\"),\n");
      out.write("    password: document.getElementById(\"password\"),\n");
      out.write("    password_confirm: document.getElementById(\"password_confirm\")\n");
      out.write("  };\n");
      out.write("  ele.email.onmouseout = function(){ //name失去焦点则检测\n");
      out.write("    checkEmail (ele.email.value);\n");
      out.write("  }\n");
      out.write("  ele.nickname.onmouseout = function(){ //nickname失去焦点则检测\n");
      out.write("\t    checkNickname(ele.nickname.value);\n");
      out.write("\t  }\n");
      out.write("  ele.password.onblur = function(){ //password失去焦点则检测\n");
      out.write("    checkPassw(ele.password.value,ele.password_confirm.value);\n");
      out.write("  }\n");
      out.write("  ele.password_confirm.onmouseout = function(){ //password_confirm失去焦点则检测\n");
      out.write("    checkPassw(ele.password.value,ele.password_confirm.value);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("\n");
      out.write("function checkNickname(name){  //验证name\n");
      out.write("   if(name != \"\"){ //不为空则正确\n");
      out.write("\t   $(\"#nickname_error\").css('display','none');\n");
      out.write("\t   $(\"#is_disable\").removeAttr(\"disabled\");    \n");
      out.write("   return true;\n");
      out.write("   }else{ //name不符合\n");
      out.write("\t   $(\"#nickname_error\").css('display','block');\n");
      out.write("       $(\"#nickname_error\").html('昵称不能为空！').css(\"color\",\"red\");\n");
      out.write("       $(\"#is_disable\").attr(\"disabled\",\"true\");  \n");
      out.write("        return false;\n");
      out.write("   }\n");
      out.write(" }\n");
      out.write(" function checkPassw(passw1,passw2){ //验证密码\n");
      out.write("\t console.log(passw1,passw2);\n");
      out.write("   if(passw1 == \"\" || passw2 == \"\" || passw1 != passw2){ //两次密码输入不为空且不等 不符合\n");
      out.write("      $(\"#confirm_error\").css('display','block');\n");
      out.write("      $(\"#confirm_error\").html(\"两次输入的密码不一致\").css(\"color\",\"red\");\n");
      out.write("       $(\"#is_disable\").attr(\"disabled\",\"true\");  \n");
      out.write("     return false;\n");
      out.write("   }else{  //密码输入正确\n");
      out.write("\t   $(\"#confirm_error\").css('display','none',\"background-color\",\"red\");\n");
      out.write("\t   $(\"#is_disable\").removeAttr(\"disabled\"); \n");
      out.write("   return true;\n");
      out.write("    \n");
      out.write("   }\n");
      out.write(" }\n");
      out.write(" function checkEmail(email){  //验证邮箱\n");
      out.write("   var pattern = /^([\\.a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(\\.[a-zA-Z0-9_-])+/; \n");
      out.write("   if(!pattern.test(email)){ //email格式不正确\n");
      out.write("\t  \n");
      out.write("       $(\"#email_error\").css('display','block');\n");
      out.write("       $(\"#email_error\").html('请填写正确的邮箱').css(\"color\",\"red\");\n");
      out.write("        $(\"#is_disable\").attr(\"disabled\",\"true\"); \n");
      out.write("          return false;\n");
      out.write("   }else{ //格式正确\n");
      out.write("\t   $(\"#email_error\").css('display','none');\n");
      out.write("\t   $(\"#is_disable\").removeAttr(\"disabled\");       \n");
      out.write("   return true;\n");
      out.write("   }\n");
      out.write(" }\n");
      out.write(" </script>\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
